esphome:
  name: inkplate13-test
  friendly_name: Inkplate 13 Test

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: components

logger:

inkplate13:
  id: my_inkplate13
